Swap.App/SwapApp.Web.MVC.UI/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AlGulumVerGulum.BLL.Abstract;
using AlGulumVerGulum.BLL.Utility.Messages;
using AlGulumVerGulum.DTO.UserDtos;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Yazilim129.CORE.Model;

namespace AlGulumVerGulum.Web.MVC.UI.Controllers
{
    public class AccountController : Controller
    {
        private readonly IUserService userService;

        public AccountController(IUserService userService)
        {
            this.userService = userService;
        }

        [Route("login")]
        public IActionResult Login(string returnUrl)
        {
            TempData["returnUrl"] = returnUrl;
            return View(new UserLoginDto());
        }

        [HttpPost]
        [Route("login")]
        public async Task<IActionResult> Login(UserLoginDto dto)
        {
            if (ModelState.IsValid)
            {
                var loginResult = userService.Login(dto);

                if (loginResult.Type == ResultType.Success)
                {
                    var claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.NameIdentifier,loginResult.Data.Id.ToString()),
                        new Claim(ClaimTypes.Email,loginResult.Data.Email),
                        new Claim(ClaimTypes.Name,loginResult.Data.Name)
                    };

                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);

                   await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                    return Redirect((string)TempData["returnUrl"]);
                }
                else
                {
                    ViewBag.Hatali = loginResult.Message;
                }
            }

            return View(dto);
        }
    }
}

Swap.App/SwapApp.Web.MVC.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AlGulumVerGulum.Web.MVC.UI.Controllers
{
    public class HomeController : Controller
    {
        [Route("/")]
        [Route("anasayfa")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Swap.App/SwapApp.Web.MVC.UI/Controllers/NoticeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AlGulumVerGulum.Web.MVC.UI.Controllers
{
    public class NoticeController : Controller
    {
        [Route("ilanlar")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("ilan-detayi")]
        public IActionResult Detail()
        {
            return View();
        }

        [Authorize]
        [Route("ilan-olustur")]
        public IActionResult CreateNotice()
        {
            return View();
        }
    }
}

Swap.App/SwapApp.Web.MVC.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@await Component.InvokeAsync("HomeBanner")

<section class="working-area working-area-two pt-100 pb-70">
    <div class="container">
        <div class="section-title green-title">
            <span>Takasım Geldi</span>
            <h2>Nasıl Çalışır?</h2>
        </div>
        <div class="row">
            <div class="col-lg-3 col-sm-6">
                <div class="single-working">
                    <i class="flaticon-tick"></i>
                    <h3>Bir İlan Yayınla</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate sint tempore.</p>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="single-working">
                    <i class="flaticon-find-my-friend"></i>
                    <h3>Aradığın İlanı Bul</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate sint tempore.</p>
                </div>
            </div>

            <div class="col-lg-3 col-sm-6">
                <div class="single-working">
                    <i class="flaticon-salary"></i>
                    <h3>Takas Teklifi Gönder</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate sint tempore.</p>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="single-working">
                    <i class="flaticon-submit"></i>
                    <h3>Takası Tamamla</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate sint tempore.</p>
                </div>
            </div>
        </div>
    </div>
</section>

@await Component.InvokeAsync("HomeCategories")
@*Banner*@
@await Component.InvokeAsync("FeatureNotices")


<div class="copy-right-area copy-right-area-two">
    <div class="container">
        <p>
            © @DateTime.Now.Year TakasEt Is Proudly Created By
            <a href="../../../envytheme.com/index.html" target="_blank">Yazılım 129</a>
        </p>
    </div>
</div>


<div class="go-top go-top-two">
    <i class="bx bx-chevrons-up"></i>
    <i class="bx bx-chevrons-up"></i>
</div>

Swap.App/SwapApp.Web.MVC.UI/Views/Notice/CreateNotice.cshtml
@{
    ViewData["Title"] = "CreateNotice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{
    <link href="~/summernote-0.8.18-dist/summernote-lite.css" rel="stylesheet" />
}

<section class="job-information-area ptb-100">
    <div class="container">
        <div class="job-information">
            <h3>İlan Bilgileri</h3>
            <form class="w-100">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label>İlan başlığı*</label>
                            <input class="form-control" type="text" name="title">
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12">
                        <div class="form-group">
                            <label>Kategori*</label>
                            <select>
                                <option value="1">UX/UI Designer</option>
                                <option value="2">Web Developer</option>
                                <option value="3">Web Designer</option>
                                <option value="4">Software Developer</option>
                                <option value="5">SEO</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="form-group">
                            <label>İl*</label>
                            <select>
                                <option value="1">Full Time</option>
                                <option value="2">Part Time</option>
                                <option value="3">Contract</option>
                                <option value="4">Internship</option>
                                <option value="5">Office</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="form-group">
                            <label>İlçe*</label>
                            <select>
                                <option value="1">Full Time</option>
                                <option value="2">Part Time</option>
                                <option value="3">Contract</option>
                                <option value="4">Internship</option>
                                <option value="5">Office</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label>İlan Detayı*</label>
                            <textarea rows="50" id="summernote" name="editordata"></textarea>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label>Kapak Resmi*</label>
                            <input type="file" class="form-control-file" />
                        </div>
                    </div>

                    <div class="col-12">
                        <div class="form-group">
                            <label>Resimler*</label>
                            <input type="file" multiple class="form-control-file" />
                        </div>
                    </div>

                    <div class="col-12">
                        <div class="form-group">
                            <button type="submit" class="btn-block default-btn btn-two">İlanı Yayınla</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

@section Scripts{
    <script src="~/summernote-0.8.18-dist/summernote-lite.js"></script>
    <script>
        $(document).ready(function () {
            $('#summernote').summernote({
                height: 450
            });
        });
    </script>
}

Swap.App/SwapApp.Web.MVC.UI/Views/Notice/Detail.cshtml
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">

    <style>
        #demo {
            height: 100%;
            position: relative;
            overflow: hidden;
        }


        .green {
            background-color: #6fb936;
        }

        .thumb {
            margin-bottom: 30px;
        }

        .page-top {
            margin-top: 85px;
        }


        img.zoom {
            width: 100%;
            height: 200px;
            border-radius: 5px;
            object-fit: cover;
            -webkit-transition: all .3s ease-in-out;
            -moz-transition: all .3s ease-in-out;
            -o-transition: all .3s ease-in-out;
            -ms-transition: all .3s ease-in-out;
        }


        .transition {
            -webkit-transform: scale(1.2);
            -moz-transform: scale(1.2);
            -o-transform: scale(1.2);
            transform: scale(1.2);
        }

        .modal-header {
            border-bottom: none;
        }

        .modal-title {
            color: #000;
        }

        .modal-footer {
            display: none;
        }
    </style>
}

<section class="job-details-area ptb-100">
    <div class="container">
        <div class="row d-none d-sm-block">
            <div class="col-lg-12">
                <div class="hot-jobs-list">
                    <div class="row">
                        <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                            <a href="https://images.pexels.com/photos/62307/air-bubbles-diving-underwater-blow-62307.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="fancybox" rel="ligthbox">
                                <img src="https://images.pexels.com/photos/62307/air-bubbles-diving-underwater-blow-62307.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="zoom img-fluid " alt="">
                            </a>
                        </div>
                        <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                            <a href="https://images.pexels.com/photos/38238/maldives-ile-beach-sun-38238.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="fancybox" rel="ligthbox">
                                <img src="https://images.pexels.com/photos/38238/maldives-ile-beach-sun-38238.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="zoom img-fluid" alt="">
                            </a>
                        </div>

                        <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                            <a href="https://images.pexels.com/photos/158827/field-corn-air-frisch-158827.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="fancybox" rel="ligthbox">
                                <img src="https://images.pexels.com/photos/158827/field-corn-air-frisch-158827.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="zoom img-fluid " alt="">
                            </a>
                        </div>

                        <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                            <a href="https://images.pexels.com/photos/302804/pexels-photo-302804.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="fancybox" rel="ligthbox">
                                <img src="https://images.pexels.com/photos/302804/pexels-photo-302804.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="zoom img-fluid " alt="">
                            </a>
                        </div>

                        <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                            <a href="https://images.pexels.com/photos/1038914/pexels-photo-1038914.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="fancybox" rel="ligthbox">
                                <img src="https://images.pexels.com/photos/1038914/pexels-photo-1038914.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="zoom img-fluid " alt="">
                            </a>
                        </div>

                        <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                            <a href="https://images.pexels.com/photos/414645/pexels-photo-414645.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="fancybox" rel="ligthbox">
                                <img src="https://images.pexels.com/photos/414645/pexels-photo-414645.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="zoom img-fluid " alt="">
                            </a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-8">
                <div class="hot-jobs-list">
                    <div class="row align-items-center">
                        <div class="col-lg-2">
                            <div class="hot-jobs-img">
                                <img src="~/telefon.jpg" alt="Image">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="hot-jobs-content">
                                <span class="sub-title font-weight-bold">Elektronik</span>
                                <h3>Nokia N66 Cep Telefonu</h3>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="hot-jobs-btn">
                                <a href="#" class="default-btn">Takas Teklifi Yap</a>
                                <p><span>İlan tarihi: </span>8 Eylül 2021</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="job-details-content">
                    <h3>Job Description</h3>
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Lorem ipsum dolor sit amet, consetetur</p>
                    <h4>Responsibilities:</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A nisi aspernatur modi doloribus dolorem quidem! Neque placeat numquam vel magni ipsam, similique eligendi sunt laudantium, nihil alias soluta eos in Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et nam eveniet quasi.</p>
                    <ul>
                        <li>Stet clita kasd gubergren, no sea takimata sanctus</li>
                        <li>Lorem ipsum dolor sit amet lorem ipsum dolor sit amet</li>
                        <li>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor</li>
                        <li>Aliquyam erat, sed diam voluptua</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="job-details-sidebar">
                    <div class="row d-sm-none">
                        <div class="col-lg-12">
                            <div class="hot-jobs-list">
                                <div class="row">
                                    <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                                        <a href="https://images.pexels.com/photos/62307/air-bubbles-diving-underwater-blow-62307.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="fancybox" rel="ligthbox">
                                            <img src="https://images.pexels.com/photos/62307/air-bubbles-diving-underwater-blow-62307.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="zoom img-fluid " alt="">
                                        </a>
                                    </div>
                                    <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                                        <a href="https://images.pexels.com/photos/38238/maldives-ile-beach-sun-38238.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="fancybox" rel="ligthbox">
                                            <img src="https://images.pexels.com/photos/38238/maldives-ile-beach-sun-38238.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="zoom img-fluid" alt="">
                                        </a>
                                    </div>

                                    <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                                        <a href="https://images.pexels.com/photos/158827/field-corn-air-frisch-158827.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="fancybox" rel="ligthbox">
                                            <img src="https://images.pexels.com/photos/158827/field-corn-air-frisch-158827.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="zoom img-fluid " alt="">
                                        </a>
                                    </div>

                                    <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                                        <a href="https://images.pexels.com/photos/302804/pexels-photo-302804.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="fancybox" rel="ligthbox">
                                            <img src="https://images.pexels.com/photos/302804/pexels-photo-302804.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="zoom img-fluid " alt="">
                                        </a>
                                    </div>

                                    <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                                        <a href="https://images.pexels.com/photos/1038914/pexels-photo-1038914.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="fancybox" rel="ligthbox">
                                            <img src="https://images.pexels.com/photos/1038914/pexels-photo-1038914.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="zoom img-fluid " alt="">
                                        </a>
                                    </div>

                                    <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                                        <a href="https://images.pexels.com/photos/414645/pexels-photo-414645.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="fancybox" rel="ligthbox">
                                            <img src="https://images.pexels.com/photos/414645/pexels-photo-414645.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" class="zoom img-fluid " alt="">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="job-widget">
                        <h3>İlan Sahibi Hakkında</h3>
                        <ul class="overview">
                            <li class="text-center">
                                <img class="rounded rounded-circle" src="~/telefon.jpg" width="150" height="150" alt="Alternate Text" />
                            </li>
                            <li><hr /></li>
                            <li>
                                Ad
                                <span>: H... T...</span>
                            </li>
                            <li>
                                TP Puanı
                                <span>: 8.8/10</span>
                            </li>
                            <li>
                                Üyelik Tarihi
                                <span>: 3 Ağustos 2021</span>
                            </li>
                            <li>
                                Aktif İlan Sayısı
                                <span>: 3</span>
                            </li>
                            <li>
                                Takas Sayısı
                                <span>: 13</span>
                            </li>

                        </ul>
                    </div>

                    <div class="job-widget">
                        <h3>İlan Hakkında</h3>
                        <ul class="overview">
                            <li>
                                Yayınlanma Tarihi
                                <span>: 3 Eylül 2021</span>
                            </li>
                            <li>
                                Alınan Teklif
                                <span>: 5</span>
                            </li>
                            <li>
                                Kategori
                                <span>: Elektronik</span>
                            </li>
                            <li>
                                Konum
                                <span>: Çankaya/Ankara</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
      
    </div>
</section>


@section Scripts{
    <script src="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>

    <script>
        $(document).ready(function () {
            $(".fancybox").fancybox({
                openEffect: "none",
                closeEffect: "none"
            });

            $(".zoom").hover(function () {

                $(this).addClass('transition');
            }, function () {

                $(this).removeClass('transition');
            });
        });
    </script>
}

Swap.App/SwapApp.Web.MVC.UI/Views/Shared/Components/FeatureNotices.cshtml
<section class="hot-jobs-area hot-jobs-area-two pb-100" id="feature-notices">
    <div class="container">
        <div class="section-title green-title">
            <span>Sıcak Takaslar</span>
            <h2>Önerilen İlanlar</h2>
        </div>
        <ul class="shorting-menu">
            <li class="filter" data-filter="all">
                Sana yakın ilanlar
            </li>
            <li class="filter" data-filter=".part-time">
                En çok teklif alanlar
            </li>
            <li class="filter" data-filter=".part-time">
                En yeni ilanlar
            </li>
            <li class="filter" data-filter="all">
                Öne çıkan ilanlar
            </li>
        </ul>
        <div class="shorting">
            <div class="row">
                @for (int i = 0; i < 10; i++)
                {
                    <div class="col-lg-12 col-md-6 mix part-time">
                        <div class="hot-jobs-list">
                            <div class="row align-items-center">
                                <div class="col-lg-2">
                                    <a href="job-details.html" class="">
                                        <img class="d-flex" src="~/telefon.jpg" alt="Image">
                                    </a>
                                </div>
                                <div class="col-lg-4">
                                    <div class="hot-jobs-content">
                                        <h3><a href="job-details.html">Elektronik</a></h3>
                                        <span class="sub-title">Nokia 7610 Cep Telefonu</span>
                                        <ul>
                                            <li><span>İlan Sahibi:</span> H... T... (8.8 TP)</li>
                                            <li><span>Teklifler: </span>3</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <ul class="deadline">
                                        <li>
                                            <i class="bx bx-location-plus"></i>
                                            Çankaya/Ankara
                                        </li>
                                        <li>
                                            <i class="bx bx-calendar"></i>
                                            İlan Tarihi: 3 Eylül 2021
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-lg-3">
                                    <div class="hot-jobs-btn">
                                        <a href="/ilan-detayi" class="default-btn btn-two">Detayları gör</a>
                                    </div>
                                </div>
                            </div>
                            <span class="featured">TP - 8.8/10</span>
                        </div>
                    </div>
                }
                <div class="col-12 text-center mt-2">
                    <a href="#" class="default-btn btn-two">Daha fazla gör</a>
                </div>
            </div>
        </div>
    </div>
</section>

Swap.App/SwapApp.Web.MVC.UI/Views/Shared/Components/HomeBanner.cshtml
<section class="banner-area banner-area-two ptb-100">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <div class="banner-content rounded px-3 p-1" style="background-color: rgba(0, 0, 0, 0.5);">
                    <h1 class="text-white">Atma, Alma, Takas Et !</h1>
                    <p class="text-white">Sayısız ilan takas teklifi bekliyor!</p>
                    <form class="search-job">
                        <div class="row">
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="job-title" placeholder="Kategori seç">
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="job-title-2" placeholder="Şehir seç">
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <a asp-controller="Notice" asp-action="CreateNotice" class="default-btn">
                                   İlan ver
                                </a>
                            </div>
                        </div>
                    </form>
                    <div class="total-job-count">
                        <div class="row">
                            <div class="col-lg-4 col-sm-6 col-md-4">
                                <div class="job-count">
                                    <h3 class="text-white"><span class="text-white">Toplam ilan sayısı: </span>9,492</h3>
                                </div>
                            </div>
                            <div class="col-lg-4 col-sm-6 col-md-4">
                                <div class="job-count">
                                    <h3 class="text-white"><span class="text-white">Takas edilen: </span>2,558</h3>
                                </div>
                            </div>
                            <div class="col-lg-4 col-sm-6 col-md-4 offset-sm-3 offset-md-0 offset-lg-0">
                                <div class="job-count">
                                    <h3 class="text-white"><span class="text-white">Takas bekleyen: </span>6,436</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Swap.App/SwapApp.Web.MVC.UI/Views/Shared/Header.cshtml
<header class="header-area sticky-top">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mx-0 px-0">
        <div class="col-2 text-center">
            @*<img src="assets/images/green-logo.png" alt="logo">*@
            <a class="pl-md-4" href="/"><img src="~/Takasdo.png" alt="Alternate Text" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse col-10" id="navbarSupportedContent">
            <div class="row col-12 justify-content-center">
                <form class="form-inline-block col-7 my-2 my-lg-0">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1"><i class="flaticon-location"></i></span>
                        </div>
                        <input class="form-control mr-sm-2" type="search" placeholder="ara" aria-label="Search">
                    </div>
                </form>
                <a asp-controller="Notice" asp-action="Index" class="default-btn btn-two col-1">
                    Ara
                </a>&nbsp;
                <a asp-action="Login" asp-controller="Account" class="btn btn-default text-right offset-1 pt-2 col-2">
                    <i class="flaticon-user-1"></i> Giriş yap / Kayıt ol
                </a>
            </div>
        </div>
    </nav>
</header>